webapi_tests/orientation/test_screen_orientation.py

Support new and old Screen Orientation API at the same time.

Bug 1037536 - Update the semiauto screen orientation test to use the latest api changes

---

webapi_tests/app_management.js

Update the AppWindowManager for CertTest App.

Bug 1142430 - [MCTS] The semiauto tests will show "Could not close CertTest App automatically..." error message.

---

certsuite/harness.py

1. import uninstall function
2. backup.restore and reboot only once
3. move uninstall before reboot

bug142442, uninstall marionette and backup.restore should only call once

---

certsuite/cert.py

Bug 1144605:single html, fix missed dm based on comment from Askeing

---

certsuite/cert.py

1. add global logger
2. use the global logger in webapi_logger_handler

Bug 1147255 - There's a missing logger for webapi_logger_handler

---

certsuite/harness.py
certsuite/report/report.css
certsuite/report/subsuite.py
certsuite/report/summary.py
certsuite/reportmanager.py

1. reduce report.css size
2. remove sortable javascript and other embedded javascript

Bug 1148271: reduce subsuite size to improve subpage load performance

---

certsuite/cert.py
certsuite/report/report.css
certsuite/report/results.py
certsuite/report/subsuite.py
certsuite/report/summary.py
certsuite/reportmanager.py

1. Add cert skip test record to final report
2. add SKIP style use cross-line to identify skipped test
3. Only add webapi test skipped cases to report
4. add skip test result to final test report
5. add device profile information to test summary report
6. fix summary report details log not clear, use ul and li
7. fix unlink temporay device profile typo
Note: web-platform-tests is not support skip though device profile now

Bug 1148270 - Skipped test should be reported in final report

---

certsuite/cert.py
certsuite/harness.py
certsuite/omni_analyzer.py

1. remove dummy parent report log entry for cert summary test
2. record subtest 'OK' for checing with Mozilla

Bug 1159599 - [MCTS] enhance cert test report

---

certsuite/expected_permissions_results/2.2.permissions.json

Update cert:permissions reference results

Bug 1159666 - [MCTS][v2.2] cert:permissions

---

certsuite/cert.py

1. add global to prevent timeout error

Bug 1161884 - [MCTS] test individual permissions encounter timeout

---

.gitignore

add *.zip and device_profile.json to gitignore

refine gitignore

---

certsuite/adb_b2g.py
certsuite/harness.py

1. add run adbd as root before check test condition
2. no need to reboot device after test condition

Bug 1164765 - run adbd as root before check test condition

---

certsuite/harness.py

1. change load config to replace '/' to os.sep in loop
2. only add --host and --port to webapi test in 'stingray' mode

Bug 1164779 - [MCTS] cert and security test report is not generated

---

mcts/harness.py
mcts/utils/logger/logmanager.py
run.bat

1. add run.bat
2. fix cannot close structured log error in windows
3. fix args.mode not found, should be self.args.mode

Bug 1166718 - [MCTS] add run.bat for windows platform

---

mcts/certsuite/cert.py
mcts/harness.py
mcts/securitysuite/filesystem.py
mcts/securitysuite/kernel.py
mcts/securitysuite/ssl.py
mcts/securitysuite/suite.py
mcts/webapi_tests/runner.py

1. fix runcertsuite '--list-tests' for stingray
2. fix webapirunner '--list-tests' for stingray
3. fix securityrunner '--list-tests' for stingray
4. add security:ssl test for stingray

Bug 1167483 - [MCTS] add security:ssl to stingray

---

mcts/utils/logger/logmanager.py

pass windowserror

---

mcts/certsuite/cert.py
mcts/harness.py
mcts/securitysuite/filesystem.py
mcts/securitysuite/kernel.py
mcts/securitysuite/ssl.py
mcts/securitysuite/suite.py
mcts/utils/device/devicehelper.py
mcts/webapi_tests/semiauto/testcase.py

1. add devicehelper
2. use devicehelper to get devicemanageradb in  cert/security/webapi tests
3. fix device_profile.json missing key issues

add devicehelper

---

MANIFEST.in

add missing config.json file in manifest.in 
@Conjuror @oouyang r?

Bug 1174975 - [MCTS][v2.2] missing config.json file while running MCTS

---

mcts/webapi_tests/moztime/test_time.py

This will make sure that time zone settings won't affect the result. (eg. pc in PDT time and phone in CST time)
Also, it looks it that it takes more than a second to set time to the time entered. Thereby, I wait for 5 seconds and then get the time back after that.
@ShakoHo, r?

fix the way moztime set function works

---

mcts/webapi_tests/mobile_message/mobile_message_test.py

I think this is pretty much the solution to problems encountered when special power removal in marionette.
@ShakoHo r?

removed special power for mobile message testing

---

mcts/webapi_tests/bluetooth/bluetooth_test.py
mcts/webapi_tests/bluetooth/test_bluetooth_discovery.py

this is modification for bluetooth v2 api

---

mcts/utils/handlers/gaiautils.py
mcts/webapi_tests/mobile_message/mobile_message_test.py
mcts/webapi_tests/telephony/telephony_test.py
mcts/webapi_tests/wip/contacts/contacts_test.py

Telephony should be fine and runs smooth now.
@ShakoHo r?

took out special power parameters, fixes for telephony webapi, and some neats

---

mcts/securitysuite/suite.py
requirements.txt

@ShakoHo r?
This also fixed a strange log output when using "runcertsuite --list".

changing requirement.txt to meet the most up-to-date situtation

---

mcts/tools/webidl/manifest_parser.py

@ShakoHo, r?
This is for generating the initial manifest of webidl in gecko.

parser tools for webidl

---

mcts/readme.txt

this is the document of generating golden sample and run cert suite tests

---

mcts/certsuite/cert.py

generate reference all at once

---

mcts/certsuite/cert.py
mcts/config.json
mcts/securitysuite/kernel.py
mcts/securitysuite/ssl.py
requirements.txt

supporting marionette extension v0.4.9 and fxos appgen v0.15 now

Marionette extension support 2.5

---

requirements.txt

locked v2.5 requirement for further action

---

mcts/webapi_tests/tcp_socket/test_tcp_socket.py
mcts/webapi_tests/wifi/test_wifi_basic.py

Webapi wifi timing issues solved and tcp webapi changes

---

webapi_tests/app_management.js
webapi_tests/certapp.py

fixed a variable undefied issue in js

---

requirements.txt

@ShakoHo 
Please review this final patch before MCTS v2.5 release.
Thank you so much.

final requirement changes for phone v2.5 release
